config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'events#index'
  devise_for :users
  resources :users, only: [:show, :edit] do
    resources :avatars, only: [:create]
  end
  resources :events do
    resources :participations
    resources :banners, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  after_create :welcome_send

  belongs_to :user
  belongs_to :event

  validates :stripe_customer_id, presence: true, uniqueness: true

  def welcome_send
    AttendanceMailer.welcome_email(self).deliver_now
  end  
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :attendances
  has_many :users, through: :attendances

  has_one_attached :banner

  validates :start_date, presence: true, unless: :start_date_cannot_be_in_the_past
  validates :duration, presence: true, numericality: { only_integer: true }
  validate :duration_is_a_multiple_of_five

  validates :title, presence: true, length: { in: 5..140 }
  validates :description, presence: true, length: { in: 20..1000 }
  validates :price, presence: true, :numericality => { :greater_than_or_equal_to => 1, :less_than_or_equal_to => 1000 }
  validates :location, presence: true
  validates :user_id, presence: true

  # Method to prevent creating past events
  def start_date_cannot_be_in_the_past
    if start_date.present? && start_date < Date.today
      errors.add(:start_date, "L'évènement ne peut pas être créer dans le passé.")
    end
  end
  
  # Method to verify multiple of 5
  def duration_is_a_multiple_of_five
    unless duration.present? && duration % 5 == 0
      errors.add(:duration, "Doit être un multiple de 5")
    end
  end

  def banner_width
    return self.banner.variant(resize: '800x400')
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :welcome_send

  has_many :events
  has_many :attendances
  has_many :events, through: :attendances

  has_one_attached :avatar

  validates :first_name, presence: true
  validates :last_name, presence: true
  # validates :description, presence: true, length: { in: 5..140 }

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

  def thumbnail
    return self.avatar.variant(resize: '200x200')
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end

end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    @user.avatar.attach(params[:avatar])
    redirect_to(user_path(@user))
  end
end

app/controllers/banners_controller.rb
class BannersController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  
  def create
    @event = Event.find(params[:event_id])
    @event.banner.attach(params[:banner])
    redirect_to @event
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create

    # Amount in cents
    @amount = 500

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :destroy, :update]
  
  def datepicker_input form, field
    content_tag :td, :data => {:provide => 'datepicker', 'date-format' => 'yyyy-mm-dd', 'date-autoclose' => 'true'} do
      form.text_field field, class: 'form-control', placeholder: 'YYYY-MM-DD'
    end
  end
    
  def index
    @events = Event.all
  end

  def new
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit 
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(post_params)
      @event.banner.attach(params[:banner])
      redirect_to @event
      flash[:success] = "Bravo"
    else
      render :edit
      flash[:danger] = "Raté"
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @attendees_of_the_event = @event.attendances
    @attendees_of_the_event.each do |attendee|
      attendee.destroy
    end
    @event.destroy
    redirect_to events_path
    flash[:success] = "L'évènement a bien été supprimé !"
  end

  def create
    @event = Event.new(
      start_date: params[:start_date],
      duration: params[:duration],
      title: params[:title],
      description: params[:description],
      price: params[:price],
      location: params[:location],
      user_id: current_user.id)

    if @event.save
      flash[:success] = "Ton évènement est sauvegardé !"
      saving_banner
      redirect_to event_path(@event.id)
    else
      flash[:error] = "Ton évènement n'a pas pu être sauvé! Merde alors :("
      render :new
    end
  end
  
  def saving_banner
    @event = Event.find(@event.id)
    @event.banner.attach(params[:banner])
  end

  private

  def post_params
    params.require(:event).permit(:title, :description, :price, :location, :duration, :start_date, :banner)
  end

end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :index, :show]

  def index
    @event = Event.find(params[:event_id])
    @attendances = @event.attendances
  end

  def show
  end

  def new
    @event = Event.find(params[:event_id])
  end

  def create
    @event = Event.find(params[:event_id])
    @attendance = Attendance.new(
      stripe_customer_id: params[:stripeToken],
      event_id: params[:event_id],
      user_id: current_user.id)

    if @attendance.save
      flash[:success] = "Ta participation a bien été ajoutée !"
      redirect_to event_path(@event.id)
    else
      flash[:error] = "Ta participation n'a pas pu être sauvé! Merde alors :("
      render :new
    end

    # Amount in cents
    @amount = @event.price

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to @event
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def user_is_the_event_admin?
    user_signed_in? && current_user == @event.user
  end

  def user_is_not_attending_the_event?
    !user_signed_in?
  end
  
  def is_user_an_attendee?
    @array = []
    @event.attendances.each do |attendee|
      @array << attendee.user.id
    end
    if user_signed_in?
      @array.include?(current_user.id)
    end
  end
end

app/helpers/participations_helper.rb
module ParticipationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/charges/create.html.erb
<h2>Merci la miff, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/events/edit.html.erb
<div class="container p-5 my-5 bg-light w-75">
  <header class="my-5">
    <h1 class="text-center">Modifier l'évènement</h1>
  </header>
  <!-- Formulaire pour modifier l'event -->
  <%= form_for @event, multipart: true do |f| %>
    <div class="form-group">
      <%= f.label "Titre" %>
      <%= f.text_field :title, class: "form-control", placeholder: @event.title %>
    </div>

    <div class="form-group">
      <%= f.label "Description" %>
      <%= f.text_area :description, class: "form-control", rows:6, placeholder: @event.description %>
    </div>

    <div class="form-row mb-4">
      <div class="col">
        <%= f.label "Prix" %>
        <%= f.number_field :price, class: "form-control", placeholder: @event.price %>
      </div>    
      <div class="col">
        <%= f.label "Location" %>
        <%= f.text_field :location, class: "form-control", placeholder: @event.location %>
      </div>
    </div>

    <div class="form-row mb-4">
      <div class="col">
        <%= f.label "Durée de l'évènement" %>
        <%= f.number_field :duration, class: "form-control", placeholder: @event.duration %>
      </div>    
      <div class="col">
        <%= f.label "Date de début" %>
        <%= f.text_field :start_date, class: "form-control", placeholder: @event.start_date.strftime("%d-%m-%Y") %>
      </div>
    </div>

    <div class="nav-links mb-5">
      <%= submit_tag "Sauvegarder", class: "btn btn-lg btn-primary m-2" %>
      <%= link_to "Supprimer l'évènement", event_path(@event.id), class: "btn btn-outline-danger btn-lg m-2", action: "delete", method: :delete, data: { confirm: "Es-tu sûr de vouloir supprimer cet évènement ?"} %>
      <%= link_to "Annuler", root_path, class: "btn btn-outline-dark btn-lg m-2" %>
    </div>
  <% end %>
</div>

app/views/events/index.html.erb
<div class="jumbotron mb-0 text-center">
  <h1 class="display-4">Bienvenue sur THP EventBrite</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <%= link_to "Crée ton évènement", new_event_path, class:"btn btn-primary btn-lg" %>
</div>

<!-- <div class="container">
  <ul class="list-group list-group-flush">
    <% @events.each do |event| %>
      <li class="list-group-item"> <%= event.title %>
      </li>
    <% end %>
  </ul>
</div>
-->
<div class="bg-light p-5">

  <div class="container">
    <h2 class="text-center pb-3 text-uppercase">Évènements</h2>
    <div class="card-columns">
      <% @events.each do |event| %>
      <div class="card text-center">
        <div class="card-body p-5">
          <h5 class="card-title h2"> <%= event.title %> </h5>
          <p class="card-text"> <span class="font-weight-bold"> <%= event.id %> </span> • <%= event.description %> </p>
          <%= link_to "Aller sur l'évènement", event_path(event.id), class:"btn btn-outline-dark btn-lg"%><br>
        </div>
      </div>
      <% end %>
    </div>

  </div>

</div>

app/views/events/new.html.erb
<div class="container text-center p-5 my-5 w-50">
  <h1>Ajoute ton évènement !</h1>
  <div class="create form-group text-left m-4">
    <%= form_tag url_for(action: 'create'), method: "post", multipart: true, class: "needs-validation", :novalidate => true do %>
      <div class="form-group">
        <%= label_tag 'Choisis un titre' %>
        <%= text_field_tag 'title', @title, class: "form-control", placeholder: "Un super titre qui casse des :)", :required => true %>
      </div>

      <div class="form-group">
        <%= label_tag 'Description' %>
        <%= text_area_tag 'description', @description, rows: 6, class: "form-control", placeholder: "Décris ton évènement de manière succinte", :required => true %>
      </div>

      <div class="form-row mb-4">
        <div class="col">
          <%= label_tag 'Prix' %>
          <%= number_field_tag 'price', @price, in: 16...99, class: "form-control", placeholder: "Prix de l'entrée", :required => true %>
        </div>
        <div class="col">
          <%= label_tag 'Lieu' %>
          <%= text_field_tag 'location', @location, class: "form-control", placeholder: "Où les choses se passent", :required => true %>
        </div>
      </div>
      
      <div class="form-row mb-4">
        <div class="col">
          <%= label_tag "La durée de l'évènement" %>
          <%= select_tag "duration", options_for_select([ 30, 60, 90 ], 30), class: 'form-control' %>
        </div>
        <div class="col">
          <%= label_tag 'Choisis une date' %>
          <%= date_field_tag(:start_date, Date.today, class: 'form-control')%>

        </div>
      </div>

      <div class="form">
          <%= label_tag 'Ajoute une bannière' %>
          <%= file_field_tag :banner %>
      </div>

      <div class="nav-links my-5 text-center">
        <%= submit_tag "Envoyer", class: "btn btn-primary btn-lg m-2" %>
        <%= link_to "Retourner à l'accueil", root_path, class: "btn btn-outline-dark btn-lg m-2" %>
      </div>
    <% end %>
  </div>  
</div>

app/views/events/show.html.erb
<div class="jumbotron-fluid">
  <div class="container">
    <header class="p-5 text-center">
    <h1 class="display-3"> <%= @event.title %> </h1>
    <h2 class="m-4"> <%= @event.description %> </h2>
    <div class="picture">
      <p><%=@event.id%></p>
      <%if @event.banner.attached?%>
        <%= image_tag @event.banner_width, alt: 'event picture', class:"w-100" %>
      <%else%>
        <p>Pas d'image d'évènement!</p>
      <%end%>
    </div>
    <% if user_is_the_event_admin? %>
      <div class="edit_banner">
        <%= form_tag event_banners_path(@event), multipart: true do %>
          <%= file_field_tag :banner %>
          <%= submit_tag "mettre à jour" %>
        <% end %>
      </div>
      <p class="h5"> <%= current_user.first_name %> tu es l'admistrateur de l'évènement </p>
    <% elsif user_is_not_attending_the_event? %>
      <p class="p">Pour participer à cet évènement, il te suffit de t'inscrire ou de te connecter à ton compte</p>
      <%= link_to "Inscription", new_user_registration_path, class:"btn btn-primary btn-lg"%>
      <%= link_to "Connexion", new_user_session_path, class:"btn btn-outline-dark btn-lg" %>
    <% elsif is_user_an_attendee? %>
      <p> Tu participes déjà à cet évènement :)</p>
    <% else %>
      <%= link_to "Rejoindre l'évènement", new_event_participation_path(@event.id), class:"btn btn-primary btn-lg my-3" %>
    <% end %>
    </header>
    <div class="container mx-auto p-5 bg-light">
      <% if user_is_the_event_admin? %>
        <%= link_to "Mon Espace évènements", event_participations_path(@event.id), class:"btn btn-primary btn-lg mb-4" %>
      <% end %>    
      <p class="h5"> Créateur de l'évènement : <%= @event.user.first_name %></p>
      <p class="h5"> Nombre de participants : <%= @event.attendances.count %> </p>
      <p class="h5"> Date de début de l'évènement : <%= @event.start_date.strftime("%d-%m-%Y")%> </p>
      <p class="h5"> Date de fin de l'évènement : à coder ! (avec une méthode)</p>
      <p class="h5"> Prix : <%= @event.price %> € </p>
      <p class="h5"> Lieu : <%= @event.location%> </p>
    </div>
    <div class="text-center my-5">
      <%= link_to "Retourner à l'accueil", root_path, class:"btn btn-outline-dark btn-lg my-5" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThpEventbrite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Montserrat', media: 'all', 'data-turbolinks-track' => true %>    
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <%= link_to root_path, class: "navbar-brand" do %>
          <i class="fas fa-american-sign-language-interpreting mr-2"></i> THP EventBrite
        <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <%= link_to 'Accueil', root_path, class: "nav-link" %>
            </li>
            <li class="nav-item active">
              <%= link_to 'Créer un évènement', new_event_path, class: "nav-link" %>
            </li>
            <% if user_signed_in? %>
              <li class="nav-item active">
                <%= link_to "Mon Profil", user_path(current_user), class: "nav-link" %>
              </li>
              <li class="nav-item active">
                <%= link_to "Se déconnecter", destroy_user_session_path, class: "nav-link", method: :delete %>
              </li>
            <% else %>
              <li class="nav-item active">
                <%= link_to "S'inscrire", new_user_registration_path, class: "nav-link" %>
              </li>
              <li class="nav-item active">
                <%= link_to "Se connecter", new_user_session_path, class: "nav-link" %>
              </li>
            <% end %>

          </ul>
          </div>
        </div>
      </nav>
    </header>

    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %> alert-dismissible fade show mb-0"><%= value %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>

    <%= yield %>

    <!-- Footer -->
    <footer class="text-center text-secondary p-5">
      <div class="my-4">
        <%= link_to root_path, class: "h1 text-decoration-none" do %>
          <i class="fas fa-american-sign-language-interpreting mr-2"></i> THP EventBrite
        <% end %>
      </div>  
      <p class="h5 mb-5">Made with <i class="fas fa-heart"></i> by <a href="http://github.com/anhek" class="">Antonin Nhek</a></p>
    </footer>

    <!-- Chargement des scripts en fin de body -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/participations/index.html.erb
<div class="container text-center p-5 my-5 bg-light">
  <h1>Liste des participants :</h1>
  <p>
    <% @attendances.each do |attendee| %>
      <h3> <%= attendee.user.first_name %> </h3>
    <% end %>
  </p>
  <%= link_to "Editer l'évènement", edit_event_path(@event.id), class:"btn btn-primary btn-lg" %>
</div>

app/views/participations/new.html.erb
<div class="container text-center p-5 my-5 bg-light">
  <h1 class="mb-3"><%= @event.title %></h1>

  <%= form_tag event_participations_path do %>
    <article>
      <% if flash[:error].present? %>
        <div id="error_explanation">
          <p><%= flash[:error] %></p>
        </div>
      <% end %>
      <h4 class="mb-3">Pour participer à cet évènement, <br> tu dois payer la modique somme de : </h4>      
      <label class="amount">
        <span class="h3"><%= @event.price %> €</span>
      </label>
    </article>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="<%= @event.title %>"
            data-amount="<%= @event.price * 100 %>"
            data-currency="eur"
            data-locale="auto"></script>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="bg-dark p-5">
  <div class="container bg-white text-center p-5 my-5 rounded">
    <%if @user.avatar.attached?%>
      <%= image_tag @user.thumbnail, alt: 'avatar' %>
    <%else%>
    <div class="bg-primary d-inline-block rounded-circle mb-4" style="height: 200px; width: 200px;">
      <%= image_tag Faker::Avatar.image("avatar", "200x200")%>
    </div>
    <%end%>
    <h1> <%= current_user.first_name %> <%= current_user.last_name %> </h1>
    <h2 class="h3"> <%= current_user.email %></h2>
    <p class="h3 my-5"> <%= current_user.description %> </p>
    <%= link_to "Modifier ses informations importantes", edit_user_registration_path, class:"" %>
    
    <h3>Changer d'avatar ?</h3>
    <%= form_tag user_avatars_path(@user), multipart: true do %>
      <%= file_field_tag :avatar %>
      <%= submit_tag "mettre à jour" %>
    <% end %>

    <hr class="my-5">

    <div class="">
    <h3>Evènements postés :</h3>
      <% current_user.events.each do |event| %>
        <h4> <%= event.title %> <%= link_to "Voir l'évènement", event_path(event.id), class:"" %></h4>
      <% end %>
    </div>
  </div>
</div>